services:
  mysql:
    image: mysql:8.4
    container_name: mysql-tarefas
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: tarefasdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: java-tarefas
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: sh -c "mvn clean compile && mvn spring-boot:run"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  db_data:
