version: "3.8"
services:
  mysql:
    image: mysql:8.4
    container_name: mysql-tarefas
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: tarefasdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  db_data:
